apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: kubernetes-workbench
spec:
  session:
    applications:
      workshop:
        enabled: false
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
